name: Enable automerge on dependabot PRs

on: pull_request
permissions: write-all

jobs:
  automerge:
    name: Enable automerge on dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Enable automerge on dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/auto-merge.yml
